arr = [1, 2, 2, 4, 1, 6, 6, 8]
print(arr)
print('数组的长度')
print(len(arr))
print('数组的第一个元素')
print(arr[0])
print('向数组末尾追加12')
arr.append(12)
print(arr)
print('向数组下标3处插入33')
arr.insert(3, 33)
print(arr)
print('删除最后一个元素')
print(arr.pop())
print(arr)
print('移除数组中的[33]元素')
arr.remove(33)
print(arr)
print('替换数组下标2的元素为222')
arr[2] = 222
print(arr)
print('数组排序')
arr.sort()
print(arr)
